/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfirmDialog: typeof import('./components/use-dialog/confirm/ConfirmDialog.vue')['default']
    DialogProvider: typeof import('./components/use-dialog/DialogProvider.vue')['default']
    NavigationBar: typeof import('./components/navigation/NavigationBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchFilterInput: typeof import('./components/search-filter-input/SearchFilterInput.vue')['default']
    ShowCard: typeof import('./components/show-card/ShowCard.vue')['default']
    ShowForm: typeof import('./components/show-form/ShowForm.vue')['default']
    ShowFormDialog: typeof import('./components/show-form-dialog/ShowFormDialog.vue')['default']
    ShowInfoDialog: typeof import('./components/show-info-dialog/ShowInfoDialog.vue')['default']
    SnackbarProvider: typeof import('./components/use-snackbar/SnackbarProvider.vue')['default']
  }
}
