/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthForm: typeof import('./components/auth-form/AuthForm.vue')['default']
    BasicInformationFormPart: typeof import('./components/show-form/BasicInformationFormPart.vue')['default']
    ConfirmDialog: typeof import('./components/use-dialog/confirm/ConfirmDialog.vue')['default']
    DialogProvider: typeof import('./components/use-dialog/DialogProvider.vue')['default']
    EpisodeForm: typeof import('./components/show-form/episode/EpisodeForm.vue')['default']
    EpisodeFormDialog: typeof import('./components/show-form/episode/EpisodeFormDialog.vue')['default']
    EpisodesFormPart: typeof import('./components/show-form/EpisodesFormPart.vue')['default']
    IconsAutocomplete: typeof import('./components/icons-autocomplete/IconsAutocomplete.vue')['default']
    NavigationBar: typeof import('./components/navigation/NavigationBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchFilterInput: typeof import('./components/search-filter-input/SearchFilterInput.vue')['default']
    SeasonForm: typeof import('./components/show-form/season/SeasonForm.vue')['default']
    SeasonFormDialog: typeof import('./components/show-form/season/SeasonFormDialog.vue')['default']
    SettingForm: typeof import('./components/setting-form/SettingForm.vue')['default']
    SettingFormDialog: typeof import('./components/setting-form-dialog/SettingFormDialog.vue')['default']
    ShowCard: typeof import('./components/show-card/ShowCard.vue')['default']
    ShowCategoriesAutocomplete: typeof import('./components/show-categories-autocomplete/ShowCategoriesAutocomplete.vue')['default']
    ShowForm: typeof import('./components/show-form/ShowForm.vue')['default']
    ShowFormDialog: typeof import('./components/show-form-dialog/ShowFormDialog.vue')['default']
    ShowInfoDialog: typeof import('./components/show-info-dialog/ShowInfoDialog.vue')['default']
    SnackbarProvider: typeof import('./components/use-snackbar/SnackbarProvider.vue')['default']
    UserShowStatusSelect: typeof import('./components/user-show-status-select/UserShowStatusSelect.vue')['default']
    WebsiteCard: typeof import('./components/website-card/WebsiteCard.vue')['default']
    WebsiteForm: typeof import('./components/website-form/WebsiteForm.vue')['default']
    WebsiteFormDialog: typeof import('./components/website-form-dialog/WebsiteFormDialog.vue')['default']
  }
}
